Repository PurgamentumSolis/Source-Code-Inspection, pull requests merged in 2024-10, with the labels that each got.

#3 fix: Alterar incremento do For
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: bug, commission

#10 Função imprimindo valor errado
  Source Code Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: bug, commission

#8 Fix/currency-validation
  Source Code Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: bug, commission

#16 função retornando null ao invés do valor correto
  Source Code Inspection/src/br/calebe/ticketmachine/core/TicketMachine.java
Labels: bug, commission

#20 Feat/imgs-to-doc
  Documentação para Wiki/Documentacao.md
Labels: enhancement

#28 troco correção da função troco das notas de 5
  Source Code Inspection/src/br/calebe/ticketmachine/core/Troco.java
Labels: bug, commission

#30 correcao na documentacao do CSU01 – Inserir dinheiro
  Documentação para Wiki/Documentacao.md
Labels: documentation

#33 Caso de ambiguidade na seção Requisitos
  Documentação para Wiki/Documentacao.md
Labels: documentation
